version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=practical-proj
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=companion_search
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U practical-proj -d companion_search"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  Auth_service:
    build: .\Auth_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://practical-proj:1@db:5432/companion_search
      - SECRET_KEY=test-secret-key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: